### ISSUE TITLE
Support version specified in separate tag

### ISSUE THREAD

**Issue by iosdeveloper** [mackuba/sparkler#4]
It looks like versions specified separately in the `<sparkle:version>` tag (not in `<enclosure>`) result in 'No versions found' status: https://github.com/mackuba/sparkler/blob/ab44adeb9886e47ba64cb3faf28327d4049e6147/app/models/feed.rb#L61

The tag is documented here: https://sparkle-project.org/documentation/publishing/#downloading-from-a-web-site

**Comment by iosdeveloper** [comment]
This works instead of line 61:

``` ruby
enclosure && (enclosure['sparkle:shortVersionString'] || enclosure['sparkle:version'])enclosure && (enclosure['sparkle:shortVersionString'] || enclosure['sparkle:version']) || (version = xml.at_xpath('//item[1]/sparkle:version')) && version.content
```

**Comment by mackuba** [comment]
Fixed ;)
